### ISSUE TITLE
Data matrix ecc 200

### ISSUE THREAD

**Issue by InnovativeInventor** [mmulqueen/pyStrich#10]
Its great that there is a python 3 port of hubarcode. When will ECC 200, the latest version of a data matrix, be supported?

**Comment by mmulqueen** [comment]
@InnovativeInventor I'm pretty sure the data matrix generated by this package is ECC 200 only.

It's been a while since I've worked on this project, but we support some of ECC200, I don't think we support the full character capacity of ECC200. When I ported pyStrich, I expanded the maximum capacity it could handle (see issue #2). However didn't go any further than that because we didn't need it for our application. Patches are welcome. It's unlikely that we'll add greater capacity ourselves in the short term.
